### ISSUE TITLE
Error en url de respuesta

### ISSUE THREAD

**Issue by rogmoreno** [saulmoralespa/magento2-payulatam#3]
Hola Saul, mira el mensaje de error que estoy obteniendo desde la ultima semana 

[05-Jun-2020 16:09:52 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getMethod() on null in /html/vendor/saulmoralespa/magento2-payulatam/Controller/Payment/Notify.php:63Stack trace:#0 /html/vendor/magento/framework/App/Action/Action.php(108): Saulmoralespa\PayuLatam\Controller\Payment\Notify->execute()#1 /html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))#2 html/vendor/magento/framework/Interception/Interceptor.php(138): Saulmoralespa\PayuLatam\Controller\Payment\Notify\Interceptor->___callParent('dispatch', Array)#3 /html/vendor/magento/framework/Interception/Interceptor.php(153): Saulmoralespa\PayuLatam\Controller\Payment\Notify\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))#4 //html/vendor/saulmoralespa/magento2-payulatam/Controller/Payment/Notify.php on line 63

**Comment by saulmoralespa** [comment]
Que versión de Magento, has intentando volver a compilar  ?

**Comment by rogmoreno** [comment]
Hola si, es 2.3.2 si he compilado un par de veces, ya tengo programado una migracion a 2.3.5-p1 pero es en un mes

**Comment by rogmoreno** [comment]
recibi un par de notificaciones y de nuevo error en la misma linea

 $method = $order->getPayment()->getMethod();
 $methodInstance = $this->_paymentHelper->getMethodInstance($method);
